### ISSUE TITLE
Criar diagramas de atividade

### ISSUE THREAD

**Issue by tiagoheineck** [plinio/matchDog#10]
Criar diagramas de atividade

**Comment by arturcalves** [comment]
@tiagoheineck você poderia fazer os diagramas de atividades no mesmo arquivo astah que coloquei no repositório.

**Comment by tiagoheineck** [comment]
Pode ser blza

**Comment by tiagoheineck** [comment]
Está na pasta um modelo inicial para que vocês possam contribuir @arturcalves  @plinio [Aqui](https://github.com/plinio/matchDog/tree/master/docs/diagramas)
