### ISSUE TITLE
Criar diagramas de classe

### ISSUE THREAD

**Issue by tiagoheineck** [plinio/matchDog#11]
Criar diagramas de classe a partir dos requisitos

**Comment by arturcalves** [comment]
Versão inicial foi criada e commitada para o repositório

![Diagrama de Classes](https://raw.githubusercontent.com/plinio/matchDog/master/docs/diagramas/DiagramaDeClasse.png)

@tiagoheineck  e @plinio gostaria que vocês validassem....
