### ISSUE TITLE
Atributos de Qualidade

### ISSUE THREAD

**Issue by tiagoheineck** [plinio/matchDog#16]
Definir os atributos de qualidade

Pegar três atributos (requisitos não funcionais)
Descrever os três atributos
Justificar porque são importantes para a aplicação
Indicar a prioridade dos mesmos

Página 77 (79 do PDF) https://drive.google.com/a/cin.ufpe.br/file/d/0Bxt1VZoj3lGuLUx2WU8xcm5mYjg/edit

Leituras complementares
http://eyefodder.com/2011/06/quality-software-non-functional-requirements.html
Página 191 dos Slides de Análise de requisitos
![sem titulo](https://cloud.githubusercontent.com/assets/5220991/8232210/438dbb32-15bd-11e5-8a6a-c5555b60ba5c.png)

**Comment by tiagoheineck** [comment]
Atualizei com algumas outras questões para  vocês darem uma olhada, se concordarem posso aperfeiçoar. Coloquem comentários no documento do drive mesmo https://docs.google.com/a/cin.ufpe.br/document/d/1VUQTDGQkqDinC23n6F4msGoFAUTm1czxsJgTH1_qThw/edit?usp=sharing

**Comment by tiagoheineck** [comment]
@plinio @arturcalves Favor revisar o documento

**Comment by arturcalves** [comment]
Pra mim está OK!!
