### ISSUE TITLE
Alterar Perfil do Dono

### ISSUE THREAD

**Issue by arturcalves** [plinio/matchDog#28]
Requisito:
Link junto da foto do usuário logado direciona para tela onde os dados cadastrais do usuário podem ser atualizados. Mesmos campos do RF02

User History Card:
https://github.com/plinio/matchDog/wiki/Cart%C3%A3o-17

**Comment by tiagoheineck** [comment]
@arturcalves , ao meu ver já está implementado isso correto?

**Comment by arturcalves** [comment]
Faltando o álbum de fotos.
