### ISSUE TITLE
Alterar Perfil do Dog

### ISSUE THREAD

**Issue by arturcalves** [plinio/matchDog#29]
O objetivo é, da mesma forma que é possível editar o perfil do Dono, também poder editar o perfil do Dog.

User History Card
https://github.com/plinio/matchDog/wiki/Cart%C3%A3o-17

**Comment by arturcalves** [comment]
@plinio  e @tiagoheineck favor validar se está ok mesmo.

**Comment by tiagoheineck** [comment]
@arturcalves está ok, só a questão de up da foto de perfil do cachorro da o seuinte erro

              
linha 69 em diante
   
      foto = @dog.foto
      end
      foto.url = params[:foto].original_filename
      foto.descricao = "Foto do Perfil"
      foto.save
      @dog.foto = foto
