### ISSUE TITLE
Colocar rodar para teste no heroku

### ISSUE THREAD

**Issue by tiagoheineck** [plinio/matchDog#36]
Colocar rodar para teste no heroku
http://matchdog.herokuapp.com/

**Comment by tiagoheineck** [comment]
@arturcalves  @plinio ver

**Comment by arturcalves** [comment]
Massa!! Funcionou... depois documenta os comandos para publicação no heroku!!

**Comment by tiagoheineck** [comment]
Ambiente de teste funcionando no heroku
