### ISSUE TITLE
Fazer Histórias de usuário

### ISSUE THREAD

**Issue by tiagoheineck** [plinio/matchDog#4]

**Comment by tiagoheineck** [comment]
Usar o rascunho
https://docs.google.com/document/d/1MTGipHy1Xx9iodsB6r9xsRaPXk5GzJAQumERaHUF3NA/edit?usp=sharing

**Comment by plinio** [comment]
Galera, não se esqueçam de colocar casos de teste para cada card (tem alguns lá sem o "verso" do card)

**Comment by tiagoheineck** [comment]
beleza, eu estava meio em dúvida de como fazer e fiz a frente e deixei o verso para fazer depois com mais embasamento
