### ISSUE TITLE
Latidas Controller

### ISSUE THREAD

**Issue by arturcalves** [plinio/matchDog#42]
Visualização:

* Ao entrar na tela de Latidas de um match deve-se exibir todas as latidas daqueles match em ordem cronologica com destaque para as novas, sugiro alguma separação visual (latidas não lidas!?)
* Além disso essas novas Latidas devem ser setados como visualizados, para zerar o contador.

Latir:
* Salvar a mensagem enviada

User History Card
https://github.com/plinio/matchDog/wiki/Cart%C3%A3o-18

**Comment by tiagoheineck** [comment]
@plinio na verdade as latidas pelo que vi ficam colocados ao lados dos matches, correto?

**Comment by tiagoheineck** [comment]
@plinio To fechando essa tarefa, o controller está pronto, vai faltar ligar no html
