### ISSUE TITLE
Revisar os Requisitos Funcionais e gerar Issues

### ISSUE THREAD

**Issue by plinio** [plinio/matchDog#8]
- Revisar os requisitos presentes na planilha #7 https://docs.google.com/spreadsheets/d/1AR5Wt9tHVvVh-l0YQpKI4TpVGz0Er2iPN7XBNEmQYXI/edit?usp=sharing
- Criar as Issues a partir de cada Requisito e colocar na planilha (campo Issue GitHub)

**Comment by arturcalves** [comment]
OK!! As issues referentes aos requisitos Funcionais foram criadas e referenciadas na planilha.
